# lychee link checker config
max-concurrency = 4
request-timeout = 20
# Skip shields.io and badges which throttle
exclude = [
  'https://img.shields.io/*'
]
# Treat rate-limited as warnings
accept = [
  '200..299', '400'
]
