name: Task
description: Generic change or maintenance
labels: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What do you want to change and why?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bulleted, observable outcomes
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any context or links
