name: semantic-pr

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

# Ensure the workflow can post the required status on fresh repos
permissions:
  contents: read
  pull-requests: read
  statuses: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@0d326f2a77431f47202778779dada9c2522d142c # v5.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
