name: semantic-pr (example)

on:
  pull_request:

permissions:
  contents: read

jobs:
  semantic_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Semantic PR title
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
