name: ci

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  blocking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Health check
        run: echo CI is alive
