name: docs

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: 20
      - name: Install markdownlint-cli (pinned)
        run: npm i -g markdownlint-cli@0.42.0
      - name: Lint markdown
        run: markdownlint "**/*.md" "!node_modules"

  linkcheck:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Link Checker
        uses: lycheeverse/lychee-action@7da8ec1fc4e01b5a12062ac6c589c10a4ce70d67
        with:
          args: --config .lychee.toml --no-progress --verbose **/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
